### PR TITLE
Use govaluate to evaluate expressions in portfolio entry

### PR DESCRIPTION
**Pull request by simon-anz**
Allow expressions such as "5*50 + 10" when entering portfolio values.
Uses https://github.com/Knetic/govaluate
See https://github.com/miguelmota/cointop/issues/110

### CODE REVIEW

**Comment by simon-anz** [comment]
Note: there is an issue with using the `/` key in this dialog - see #150

**Comment by miguelmota** [comment]
oh wow this is an amazing feature.

I'm going to try to fix #150 before merging this in.

**Comment by miguelmota** [comment]
Merged PR. Thanks!

I moved [some things](https://github.com/miguelmota/cointop/commit/08e81cabb8476115fe54bfdaff73153fd0794893) around for reusability in another commit.

**Comment by simon-anz** [comment]
@miguelmota something in the <master> code (or my build?) appears to be making this more crashy? For example enter "xxx" as the expression:

```
$ ./bin/cointop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1342286]

goroutine 1 [running]:
github.com/Knetic/govaluate.makeParameterStage.func1({0x19b5108, 0x0}, {0x0, 0xc000830d38}, {0x0, 0x0})
	/Users/robers11/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/evaluationStage.go:217 +0x26
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x14fdc0e, 0x22}, 0x1, {0xc000288090, 0x1, 0x1}, 0xc00008ca00, {0xc0008a7165, 0x3}}, 0xc00008ca00, ...)
	/Users/robers11/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:228 +0x523
github.com/Knetic/govaluate.EvaluableExpression.Eval({{0x14fdc0e, 0x22}, 0x1, {0xc000288090, 0x1, 0x1}, 0xc00008ca00, {0xc0008a7165, 0x3}}, {0x0, ...})
	/Users/robers11/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:159 +0x115
github.com/Knetic/govaluate.EvaluableExpression.Evaluate({{0x14fdc0e, 0x22}, 0x1, {0xc000288090, 0x1, 0x1}, 0xc00008ca00, {0xc0008a7165, 0x3}}, 0x0)
	/Users/robers11/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:134 +0xf2
github.com/miguelmota/cointop/pkg/eval.EvaluateExpressionToFloat64({0xc0008a7165, 0xc000cc389c})
	/Users/robers11/src/github/cointop/pkg/eval/eval.go:20 +0x15b
```

Will raise issue.

**Comment by simon-anz** [comment]
govaluate doesn't appear to be actively maintained.  I wonder if there's a better alternative?

**Comment by simon-anz** [comment]
Google found:
- https://github.com/maja42/goval
- https://github.com/antonmedv/expr

Some other projects migrated
- https://github.com/casbin/casbin/issues/742

Sorry maybe I mad a bad choice.

**Comment by simon-anz** [comment]
#154

**Pull request merged**
