### PR TITLE
Formatting numeric and monetary values according to user's locale

### PR DESCRIPTION
**Pull request by afh**
This PR adds support to format numbers using locales specified in the `LC_NUMERIC` and `LC_MONETARY` environment variables via [`x/text/message` printer](https://pkg.go.dev/golang.org/x/text/message#example-Printer-Numbers).

In order to properly format numbers according to their meaning, i.e. number (e.g. `1h_change`) or currency (e.g. `price`) the `Comma*f` functions have been replaced with custom `Numericf` and `Monetaryf` functions.

To test run: `LC_NUMERIC=bn LC_MONETARY=de-CH go run .`, which will display currency in a Swiss German format and numbers in Bengali. This will allow people to view the cointop numeric and monetary values in their favourite format:

```
   ▲[r]ank  [n]ame            [s]ymbol     €[p]rice   [1]H%   [2]4H%    [7]D%       24H [v]olume       [m]arket cap   [a]vailable supply     [t]otal supply   last [u]pdated
  *     1   Bitcoin           BTC        467’864.00  -০.৮৭%   -৮.২৬%   -৮.৬৫%    814’660’896’107  8’748’772’383’916          ১,৮৬,৮৫,৬৭৫        ২,১০,০০,০০০  17:34:53 Apr 18
  *     2   Ethereum          ETH         18’098.44  -০.৩৭%   -৯.৩১%   -১.০৯%    484’690’957’067  2’092’856’791’162         ১১,৫৫,২০,৮৭৯       ১১,৫৫,২০,৮৭৯  17:35:12 Apr 18
        3   Binance Coin      BNB          3’946.54   ১.৬৭%   -৯.৪৪%   -২.০৫%     63’228’874’268    610’341’951’978         ১৫,৪৫,৩৩,৬৫১       ১৭,০৫,৩৩,৬৫১  17:34:44 Apr 18
        4   XRP               XRP             11.26   ০.৬৪%  -১৫.৮০%   -৩.৮৫%    152’030’449’415    515’275’538’063      ৪৫,৯৭,৩৩,১৮,০৫৬  ১,০০,০০,০০,০০,০০০  17:35:59 Apr 18
        5   Tether            USDT             8.46  -০.০২%    ০.৪৫%   -০.৯১%  1’831’827’779’717    407’461’927’782      ৪৮,১৮,৭১,৯১,৪৯৯    ৪৮,১৮,৭১,৯১,৪৯৯  17:06:52 Apr 18
        6   Dogecoin          DOGE             2.61  -১.৫০%   ১৮.৪৭%  ৩৭৯.৩৫%    200’643’707’551    340’692’607’772    ১,২৯,২৩,৭৯,৭১,৭১০  ১,২৯,২৩,৭৯,৭১,৭১০  17:35:04 Apr 18
```
        
        
image

### CODE REVIEW

**Comment by miguelmota** [comment]
This is awesome! works as expected.

Code changes look good. Will merge 👍

**Comment by miguelmota** [comment]
It would make sense to make this a config file option as well in near future.

Do you think it makes sense to also change the formatting based on user's currency selection? I'm not really familiar with international currency formatting so could any suggestions here : )

**Comment by afh** [comment]
@miguelmota I think making it a configuration option would duplicate the functionality that exists with `locale (1)`. I'd advise at documenting how to use `LC_MONETARY` and `LC_NUMERIC` with cointop.
For example should someone want to see cointop with numeric and monetary values with a different locale than the set one in their environment it is possible to invoke cointop via `/usr/bin/env LC_MONETARY=bn cointop` without needing to change the user's environment.

Where is the content for https://docs.cointop.sh/faq/ managed? The above might make a good addition the the FAQ.

In my mind it does not make sense to switch the formatting with the user's current currency selection in cointop. As a European I'm used to reading numbers with a dot `.` as a thousands separator and a comma as a decimal separator, e.g. `¤ 1.234,45`, regardless of what the currency is format is in the currency's country of origin.

It also poses the problem of which formatting to use for EUR as there are multiple ones?

| Locale | thousands separator | decimal separator |
| --- | --- | --- |
| `de_DE.UTF-8` | `.` | `,` |
| `de-CH` | `’` | `,` |
| `fr-FR.UTF-8` | ` ` _(space)_ | `,` |

**Comment by miguelmota** [comment]
@afh The FAQ markdown file is located under https://github.com/miguelmota/cointop/blob/master/docs/content/faq.md

Based on your response we'll leave it as is and add information about these environment variables and configuration to the documentation pages.  The table helped me understand better. Thanks!

**Comment by afh** [comment]
Thanks, @miguelmota 👍 

Yes, I think we should leave it as is and add documentation. I went ahead and put up #122 for review to address this.

Glad to hear the table proved helpful :)

**Comment by miguelmota** [comment]
Thanks!

**Pull request merged**
