### PR TITLE
When building portfolio slice, include highest-rank matching coin only

### PR DESCRIPTION
**Pull request by simon-anz**
See https://github.com/miguelmota/cointop/issues/130

### CODE REVIEW

**Comment by simon-anz** [comment]
This may not always be the correct solution - but I don't know how author intends to use duplicate coins.

**Comment by lyricnz** [comment]
This "fixes" a bug where duplicate coins are all added to a portfolio, because data source includes multiple results for the same symbol.

**Comment by miguelmota** [comment]
@simon-anz Thanks for the PR! 

I think it works good for removing duplicates when symbols (or where the name is a symbol) are used in the config file, however when adding multiple unique entries by name like when done via the GUI (but with some having same symbols) then not all entries are shown.

For example, when having `holdings = [["Binance-Peg Bitcoin Cash", "1"], ["Bitcoin Cash", "1"], ["XRP", "1"]]` the expected behavior would be to show all 3 entries, but it only shows 2 because the second one with same symbol is skipped.

Expected

DeepinScreenshot_select-area_20210822034749

Actual

DeepinScreenshot_select-area_20210822034801

I'm going to merge this since it'll solve the majority of issues around duplicate entries and fix the regression issue in a separate commit.

Thanks again!

**Comment by simon-anz** [comment]
Agree on the regression, though it seems a fairly unlikely situation - where someone holds two positions in BCH and wants them priced (and included in total) separately.

**Pull request merged**
