### PR TITLE
Fixes miguelmota/cointop#48

### PR DESCRIPTION
**Pull request by hmble**
Hey @miguelmota this is a small fix to issue #48. Any suggestions ?

### CODE REVIEW

**Comment by miguelmota** [comment]
@hmble PR looks great! there's some minor suggestions and then we can get it merged

**Comment by hmble** [comment]
I am happy to help. What is your suggestion ?

**Comment by miguelmota** [comment]
@hmble Sorry forgot to submit the review! They are now in the comments above

**Comment by miguelmota** [comment]
Made the changes since they were simple enough and merged your PR @hmble . It'll be available in the new release next week.

**Comment by hmble** [comment]
Thanks

**Pull request merged**
