### PR TITLE
Table column alignment

### PR DESCRIPTION
**Pull request by afh**
When using `"default"` as a fore- and background color I noticed that the table columns would no longer align. The cause seems to be that when determining the length of strings to calculate the width of columns the ANSI escapes codes colouring the text are counted too.

image

I'm uncertain whether I've properly updated the go dependencies and vendor directory, please triple check the changes; thanks 🙂  🙏

### CODE REVIEW

**Comment by miguelmota** [comment]
@afh great find and fix. Looks like the previous PR merges created conflicts with this one. Happy to merge after they're resolved. Additionally I think it'd be best for this PR to only contain the modified source files and not the go mod updates. I'll update the vendor dependencies separately.

Thanks!

**Comment by afh** [comment]
Thanks for reviewing and merge the PRs! Glad you found them helpful. As requested I've resolved the merge conflicts and reverted the commit updating the vendor dependencies.

**Comment by afh** [comment]
ℹ️ Tests fail due to missing dependencies and vendor code:
`cannot find module providing package github.com/acarl005/stripansi:`

**Comment by miguelmota** [comment]
@afh looks good, thanks! Merging.

**Pull request merged**
