### PR TITLE
Simplify rank cell color handling

### PR DESCRIPTION
**Pull request by afh**
I believe the code handling the color for the rank cell can be made more similar to the other cell handling code…

### CODE REVIEW

**Comment by miguelmota** [comment]
@afh I noticed that these updates changed the rank number color as well while before the rank color remained the default text color and only star and name were highlighted. My preference is to not highlight the rank number since it adds additional unnecessary emphasis to the number. What do you think?

**Comment by afh** [comment]
For me changing the background color for the favourite character and the name, but not the rank where the order of the columns is favourite character, rank, and name adds visual noise.
Especially as the favourite character is part of the rank column and cannot be placed elsewhere

What are your thoughts on introducing a separate `favourite` column, so that its column position can be configured with the `columns` configuration directive?

**Comment by miguelmota** [comment]
@afh a separate favorites column would be nice to have. I'm going to merge this change in since I'm not strongly oppose to it and we can offer more customization options in the future. Thanks!

**Comment by afh** [comment]
Thanks for merging this, @miguelmota.

I have a buggy version of the separate favourite column running, I'll put up a PR for review soon, there are still some things I haven't understood about how the tables are rendered. I'll ask for your expertise on the PR if I'm not able to resolve the issues…

**Comment by miguelmota** [comment]
@afh sounds good. Happy to help anywhere I can since the code is not the cleanest

**Pull request merged**
