### PR TITLE
Switch to github.com/antonmedv/expr for expression evaluation

### PR DESCRIPTION
**Pull request by simon-anz**
Rather than using govaluate, which appears to be unmaintained (and has bugs), we should switch to a different expression engine.  See #152 for bug-report about crash, and #149 for the PR that added govaluate.

Needs review:
- If you use ints in the expression, there is no automatic promotion to floats so "5/2" = 2
- I don't really understand golang type conversion: this PR checks for float64 and then int
- I don't really understand golang package management

### CODE REVIEW

**Comment by simon-anz** [comment]
Submitted an issue/question on expr, asking how to make the calculations use float by default. https://github.com/antonmedv/expr/issues/202

**Comment by simon-anz** [comment]
@miguelmota should we

1. add a FAQ describing integer arithmetic like: "Note: If the expression uses whole numbers, then the calculation will be done using whole numbers, and may not be what you expect. For example, if you enter an expression "5/2" this will resolve to "2".  If you want to ensure decimal precision, use "5.0/2""

2. fiddle with the expression before parsing, to turn int into float?  Something like

	// kludge: replace int with float
	re := regexp.MustCompile(`(?s)([^.])(\d+)([^.])`)
	input = strings.TrimSpace(re.ReplaceAllString(" "+input+" ", "$1$2.0$3"))

(this wraps input in spaces, appends \d+ with ".0" where the digits aren't surrounded by ".", then strips the whitespace again)

I have both changes here.

**Comment by simon-anz** [comment]
Okay, figured out how to dynamically update Integer => Float64 using the AST Visitor in eval (rather than kludging it with a regex). Updated PR.

**Comment by simon-anz** [comment]
OK, here's a crazy idea - provide the current coin as context to the evaluation.  I'm not sure exactly how _useful_ this is, but this allows you to use expressions like `Price/1000` to work out how many units you bought for $1000, or `Holdings*2` to double your position.  Feel free to disable it!

**Comment by miguelmota** [comment]
Hey @simon-anz this is a great fix! and really like the extra touch with the environment context. Works great!

**Comment by miguelmota** [comment]
Merged. Thanks for the PR!!

**Pull request merged**
